--DROP  SCHEMA IF EXISTS Oblig1-Oppgave4 CASCADE; --Uncomment for å slette og lage alt på nytt.
--CREATE SCHEMA Oblig1-Oppgave4;
--SET search_path TO Oblig1-Oppgave4;


DROP TABLE IF EXISTS FACULTY;
CREATE TABLE FACULTY(
	fCode varchar(3),
	fName varchar(80),
	fPhoneNr varchar(10),
	fAddress varchar(80),
	CONSTRAINT FacultyPK PRIMARY KEY (fCode)
);

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE(
	cCode varchar(6),
	cName varchar(80),
	cYear date,
	CONSTRAINT CoursePK PRIMARY KEY (cCode)
);

DROP TABLE IF EXISTS TEACHER;
CREATE TABLE TEACHER(
	TeacherID varchar(6),
	tName varchar(80),
	fCode varchar(3),
	CONSTRAINT TeacherPK PRIMARY KEY (TeacherID),
	CONSTRAINT FacultyFK FOREIGN KEY (fCode) REFERENCES FACULTY(fCode)
);
DROP TABLE IF EXISTS PROGRAM;
CREATE TABLE PROGRAM(
	ProgID MEDIUMINT NOT NULL AUTO_INCREMENT,
	progName varchar(80),
	CONSTRAINT ProgramPK PRIMARY KEY (ProgId)
);

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT(
	DepID MEDIUMINT NOT NULL AUTO_INCREMENT,
	DepName varchar(80),
	fCode varchar(3),
	CONSTRAINT DepartmentPK PRIMARY KEY (DepID),
	CONSTRAINT FacultyFKdep FOREIGN KEY (fCode) REFERENCES FACULTY(fCode)
);

DROP TABLE IF EXISTS COURSE_SCEDULE;
CREATE TABLE COURSE_SCEDULE(
	SchedID MEDIUMINT NOT NULL AUTO_INCREMENT,
	cYear date,
	TeacherID varchar(6),
	cCode varchar(6),
	CONSTRAINT Course_SchedulePK PRIMARY KEY (SchedID),
	CONSTRAINT TeacherFK FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID),
	CONSTRAINT CourseFK FOREIGN KEY (cCode) REFERENCES COURSE(cCode)
);

DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT(
	StudentID VARCHAR(6),
	BirthID VARCHAR(11),
	sName VARCHAR(80),
	curAddress VARCHAR(80),
	sPhoneNr VARCHAR(11),
	homAddress VARCHAR(80),
	bDate DATE,
	Gender VARCHAR(10),
	sYear INTEGER,
	level VARCHAR(10),
	fCode VARCHAR(3),
	ProgID MEDIUMINT NOT NULL,
	DepID MEDIUMINT NOT NULL,
	CONSTRAINT StudentPK PRIMARY KEY (StudentID),
	UNIQUE KEY (BirthID),
	CONSTRAINT FacultyFKstud FOREIGN KEY (fCode) REFERENCES FACULTY(fCode),
	CONSTRAINT ProgramFKstud FOREIGN KEY (ProgID) REFERENCES PROGRAM(ProgID),
	CONSTRAINT DepartmentFKstud FOREIGN KEY (DepID) REFERENCES DEPARTMENT(DepID)
);

DROP TABLE IF EXISTS GRADES;
CREATE TABLE GRADES(
	GradeID MEDIUMINT NOT NULL AUTO_INCREMENT,
	cYear DATE,
	cCode varchar(6),
	StudentID VARCHAR(6),
	CONSTRAINT GradePK PRIMARY KEY (GradeID),
	CONSTRAINT CourseFKgrade FOREIGN KEY (cCode) REFERENCES COURSE(cCode),
	CONSTRAINT StudentFKgrade FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID)
);
