CREATE TABLE TheTable (
	id SMALLINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	name varchar(25) NOT NULL,
	note varchar(25) NOT NULL,
	CONSTRAINT TheTablePK PRIMARY KEY (id)
);

CREATE TABLE LogTable (
	id SMALLINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	changeTimeStamp DATE,
	action varchar(8),
	tableId SMALLINT(1) UNSIGNED NOT NULL, 
	name varchar(25) NOT NULL,
	note varchar(25) NOT NULL,
	CONSTRAINT LogPK PRIMARY KEY (id)
);


CREATE TABLE AnotherTable (
	id SMALLINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	name varchar(25) NOT NULL,
	note varchar(25) NOT NULL,
	CONSTRAINT TheTablePK PRIMARY KEY (id)
)WITH SYSTEM VERSIONING;

CREATE TABLE teacher(
	id SMALLINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(80),
	salary DOUBLE NOT NULL CHECK(salary BETWEEN 1000 AND 100000),
	bonus DOUBLE,
	total DOUBLE as (bonus+salary),
	CONSTRAINT teacherPK PRIMARY KEY (id) 
);

